BEGIN
    PKG_ANALYTICS.PRC_CALCULAR_METRICAS_DIARIAS(p_usuario_id => 1, p_data => TRUNC(SYSDATE));
END;
/

BEGIN
    PKG_ANALYTICS.PRC_EXPORT_METRICAS_JSON(1, TRUNC(SYSDATE, 'MM'), SYSDATE);
END;
/

BEGIN
    PKG_ANALYTICS.PRC_EXPORT_RELATORIOS_JSON(1);
END;
/
